### ISSUE TITLE
dosen't work

### ISSUE THREAD

**Issue by nonetrix** [Rubydesic/minecraft-dynamic-discs#2]
it didn't work at first because it didn't have execute permissions on the youtube-dl script but it was easy to fix with chmod +x but now it does this

Error executing task on Sound executor
java.lang.IllegalArgumentException: Invalid audio format: PCM_SIGNED 44100.0 Hz, 32 bit, mono, 8 bytes/frame, little-endian
	at net.minecraft.class_4230.method_19685(class_4230.java:86)
	at net.minecraft.class_4231.method_19686(class_4231.java:29)
	at net.minecraft.class_4231.method_19688(class_4231.java:58)
	at net.minecraft.class_4224.method_19640(class_4224.java:154)
	at net.minecraft.class_4224.method_19643(class_4224.java:140)
	at net.minecraft.class_1140.method_19755(class_1140.java:402)
	at net.minecraft.class_4235$class_4236.method_19737(class_4235.java:34)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.class_4238.method_19765(class_4238.java:42)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Rubydesic** [comment]
I have seen this issue from another user but I currently do not have a machine running linux to test this. Looks like velvet video decodes to 32 bits PCM sample size on linux which OpenAL cannot handle. The solution is I imagine to convert the 32 bits sample into 16 bits.

**Comment by cyrneko** [comment]
> I have seen this issue from another user but I currently do not have a machine running linux to test this. Looks like velvet video decodes to 32 bits PCM sample size on linux which OpenAL cannot handle. The solution is I imagine to convert the 32 bits sample into 16 bits.

i can gladly test for you
